### ISSUE TITLE
ASGITestClient response type

### ISSUE THREAD

**Issue by ashleysommer** [sanic-org/sanic-testing#11]
After doing some mypy analysis, I've determined that the ASGITestClient `request()` method doesn't actually return a Sanic HTTPResponse, but instead a HTTPX Response object. Is this intended? Looks like theres an attempt to make it compatibile with a Sanic response object by adding in some extra attributes? Was that just to get some tests passing?

```
        response.status = response.status_code
        response.body = response.content
        response.content_type = response.headers.get("content-type")
```

Should we try to construct and return a real Sanic HTTPResponse here instead?

**Comment by ashleysommer** [comment]
Also unrelated, I notice it looks like there's two different mechanisms in place to try to capture the `request` passed into the HTTPX request. 

There is the special `TestASGIApp`  which calls the app, then returns the `request` back to the caller. That result is in-turn returned by the `app_call_with_return` function. But stepping through the code, it looks like the HTTPX runner ignores the return from that call anyway, so that saved request is discarded. 

The other method of capturing the request is similar to that done by the `SanicTestClient`, using a middleware, then saving the request against the ASGITestClient instance. This works as long as there is not two async requests running simultaneously, if that happens there will be a race-condition where the second gathered request will overwrite the saved one before it is returned to the caller.

**Comment by ahopkins** [comment]
>  Is this intended? Looks like theres an attempt to make it compatibile with a Sanic response object by adding in some extra attributes? Was that just to get some tests passing?


Yes, the intent was mere some duck typing. I believe there was a specific reason I was trying to use the `httpx` object (actually, at the time I think it was `requests-async`) for reusing connections in the Keep Alive tests. But, I think we have probably outgrown that so we could recast.

> This works as long as there is not two async requests running simultaneously, if that happens there will be a race-condition where the second gathered request will overwrite the saved one before it is returned to the caller.

Definitely a bug.
