### ISSUE TITLE
Conflict between sanic-testing 0.3.1 and strongly recommended 0.18.1 version of httpx.

### ISSUE THREAD

**Issue by ergoproxxxy** [sanic-org/sanic-testing#17]
https://www.python-httpx.org/

> We believe we've got the public API to a stable point now, but would strongly recommend pinning your dependencies to the 0.18.* release, so that you're able to properly review API changes between package updates.

```
The conflict is caused by:
    sanic-testing 0.3.1 depends on httpx<0.18 and >=0.16
```

**Comment by ahopkins** [comment]
Thanks. It is wonderful to hear the API is stable. This has been a huge problem the last several years and is one of the driving reasons `sanic-testing` was moved to its own package.

**Comment by ahopkins** [comment]
The good news is that I just ran it locally, and all the tests passed :tada:
