### ISSUE TITLE
Allow httpx 0.23.0

### ISSUE THREAD

**Issue by novotl** [sanic-org/sanic-testing#38]
`httpx` < 0.23.0 contains security vulnerability https://github.com/advisories/GHSA-h8pj-cxx2-jfg2 that was fixed in `httpx  = 0.23.0` in:
- https://github.com/encode/httpx/issues/2184

The version containing the hotfix is currently not allowed

https://github.com/sanic-org/sanic-testing/blob/04b1b9672ba18726283697bae84e20bf0a8b684d/setup.py#L49-L51

**Comment by ahopkins** [comment]
Thanks. I have been very hesitant to release the upper bound because of the history of the project to introduce breaking changes.

**Comment by ahopkins** [comment]
@novotl Looks like it runs okay. Would you submit a PR for the change?

**Comment by erickg-k** [comment]
@ahopkins What's your opinion using aiohttp?
