### ISSUE TITLE
sanic 21.12 compatibility

### ISSUE THREAD

**Issue by staden** [sanic-org/sanic-testing#58]
sanic-testing 22.9 breaks compatibility with sanic 21.12:
```
>>> from sanic import Sanic
>>> app = Sanic('app')
>>> app.test_client.get('/')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/.../python3.9/site-packages/sanic_testing/testing.py", line 288, in get
    return self._sanic_endpoint_test("get", *args, **kwargs)
  File "/.../python3.9/site-packages/sanic_testing/testing.py", line 237, in _sanic_endpoint_test
    self.app.run(  # type: ignore
TypeError: run() got an unexpected keyword argument 'single_process'
```
sanic-testing 22.6 works though

**Comment by ahopkins** [comment]
Generally, you are advised to use the version corresponding to the core version.

**Comment by ahopkins** [comment]
Not sure we should plan to add backwards compat for this.

**Comment by sjsadowski** [comment]
@ahopkins I don't think so, but we should probably pin sanic-testing to its matching version and probably document the fact that sanic-testing should match the core version.
