### ISSUE TITLE
Incorrect Return type on _sanic_endpoint_test

### ISSUE THREAD

**Issue by ashleysommer** [sanic-org/sanic-testing#6]
_sanic_endpoint_test can return `response` or `(request, response)` depending if `gather_request` is specified.

Tuple and Union are around the wrong way.
```
typing.Tuple[typing.Union[Request, HTTPResponse]]
```

Should be
```
typing.Union[typing.Tuple[Request, HTTPResponse], HTTPResponse]
```

**Comment by ahopkins** [comment]
Maybe we should change it to always a `tuple`:

```
Tuple[Optional[Request], HTTPResponse]
```

**Comment by ashleysommer** [comment]
As part of #7 changes, I also changed the ASGITestClient `request()` method to return either `response` or `(request, response)` depending on whether `gather_request` was set, so it would match the way SanicTestClient works.

But I agree, I think both should actually return `Tuple[Optional[Request], HTTPResponse]`
